Autogenerated tree updates.
merged:

  faustoo: 8cf33f71adbf52974f1e4f8443ef40cfd7de3969
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: f257ef748d9bfd964867485ea1114c6bb9d49d35

diff --git a/app-admin/rsyslog/templates/rsyslog.tmpl b/app-admin/rsyslog/templates/rsyslog.tmpl
--- a/app-admin/rsyslog/templates/rsyslog.tmpl
+++ b/app-admin/rsyslog/templates/rsyslog.tmpl
@@ -1,35 +1,42 @@
-# Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI="6"
-PYTHON_COMPAT=( python{2_7,3_5,3_6,3_7} )
+EAPI="7"
+PYTHON_COMPAT=( python3+ )
 
-inherit autotools eutils linux-info python-any-r1 systemd
+inherit autotools linux-info python-any-r1 systemd
 
 DESCRIPTION="An enhanced multi-threaded syslogd with database support and more"
 HOMEPAGE="https://www.rsyslog.com/"
+SRC_URI="{% for flag in artifacts %}
+	{% if loop.first %}{{ artifacts[flag].src_uri }}{% endif %}
+	{{ flag }}? ( {{ artifacts[flag].src_uri }} )
+{% endfor %}"
 
-if [[ ${PV} == "9999" ]]; then
-	EGIT_REPO_URI="https://github.com/rsyslog/${PN}.git"
-
-	DOC_REPO_URI="https://github.com/rsyslog/${PN}-doc.git"
-
-	inherit git-r3
-else
-	KEYWORDS="~amd64 ~arm ~arm64 ~hppa ~x86"
-
-	SRC_URI="
-		https://www.rsyslog.com/files/download/${PN}/${P}.tar.gz
-		doc? ( https://www.rsyslog.com/files/download/${PN}/${PN}-doc-${PV}.tar.gz )
-	"
-fi
-
+KEYWORDS="*"
 LICENSE="GPL-3 LGPL-3 Apache-2.0"
 SLOT="0"
-IUSE="curl dbi debug doc elasticsearch +gcrypt gnutls jemalloc kafka kerberos kubernetes libressl mdblookup"
-IUSE+=" mongodb mysql normalize clickhouse omhttp omhttpfs omudpspoof openssl postgres"
-IUSE+=" rabbitmq redis relp rfc3195 rfc5424hmac snmp ssl systemd test usertools +uuid xxhash zeromq"
+
+IUSE="clickhouse curl dbi debug doc elasticsearch +gcrypt gnutls imhttp"
+IUSE+=" impcap jemalloc kafka kerberos kubernetes mdblookup"
+IUSE+=" mongodb mysql normalize omhttp omhttpfs omudpspoof +openssl"
+IUSE+=" postgres rabbitmq redis relp rfc3195 rfc5424hmac snmp +ssl"
+IUSE+=" systemd test usertools +uuid xxhash zeromq"
+
 RESTRICT="!test? ( test )"
+
+REQUIRED_USE="
+	kubernetes? ( normalize )
+	ssl? ( || ( gnutls openssl ) )
+"
+
+BDEPEND=">=sys-devel/autoconf-archive-2015.02.24
+	virtual/pkgconfig
+	elibc_musl? ( sys-libs/queue-standalone )
+	test? (
+		jemalloc? ( <sys-libs/libfaketime-0.9.7 )
+		!jemalloc? ( sys-libs/libfaketime )
+		${PYTHON_DEPS}
+	)"
 
 RDEPEND="
 	>=dev-libs/libfastjson-0.99.8:=
@@ -39,15 +46,20 @@ RDEPEND="
 	dbi? ( >=dev-db/libdbi-0.8.3 )
 	elasticsearch? ( >=net-misc/curl-7.35.0 )
 	gcrypt? ( >=dev-libs/libgcrypt-1.5.3:= )
+	imhttp? (
+		dev-libs/apr-util
+		www-servers/civetweb
+		virtual/libcrypt:=
+	)
+	impcap? ( net-libs/libpcap )
 	jemalloc? ( >=dev-libs/jemalloc-3.3.1:= )
 	kafka? ( >=dev-libs/librdkafka-0.9.0.99:= )
 	kerberos? ( virtual/krb5 )
 	kubernetes? ( >=net-misc/curl-7.35.0 )
 	mdblookup? ( dev-libs/libmaxminddb:= )
 	mongodb? ( >=dev-libs/mongo-c-driver-1.1.10:= )
-	mysql? ( virtual/libmysqlclient:= )
+	mysql? ( dev-db/mysql-connector-c:= )
 	normalize? (
-		>=dev-libs/libee-0.4.0
 		>=dev-libs/liblognorm-2.0.3:=
 	)
 	clickhouse? ( >=net-misc/curl-7.35.0 )
@@ -59,45 +71,23 @@ RDEPEND="
 	relp? ( >=dev-libs/librelp-1.2.17:= )
 	rfc3195? ( >=dev-libs/liblogging-1.0.1:=[rfc3195] )
 	rfc5424hmac? (
-		!libressl? ( >=dev-libs/openssl-0.9.8y:0= )
-		libressl? ( dev-libs/libressl:= )
+		>=dev-libs/openssl-0.9.8y:0=
 	)
 	snmp? ( >=net-analyzer/net-snmp-5.7.2 )
 	ssl? (
 		gnutls? ( >=net-libs/gnutls-2.12.23:0= )
 		openssl? (
-			!libressl? ( dev-libs/openssl:0= )
-			libressl? ( dev-libs/libressl:0= )
+			dev-libs/openssl:0=
 		)
 	)
 	systemd? ( >=sys-apps/systemd-234 )
 	uuid? ( sys-apps/util-linux:0= )
 	xxhash? ( dev-libs/xxhash:= )
 	zeromq? (
-		>=net-libs/czmq-3.0.2
-	)"
-DEPEND="${RDEPEND}
-	>=sys-devel/autoconf-archive-2015.02.24
-	virtual/pkgconfig
-	elibc_musl? ( sys-libs/queue-standalone )
-	test? (
-		>=dev-libs/liblogging-1.0.1[stdlog]
-		jemalloc? ( <sys-libs/libfaketime-0.9.7 )
-		!jemalloc? ( sys-libs/libfaketime )
-		${PYTHON_DEPS}
+		>=net-libs/czmq-4:=[drafts]
 	)"
 
-REQUIRED_USE="
-	kubernetes? ( normalize )
-	ssl? ( || ( gnutls openssl ) )
-"
-
-if [[ ${PV} == "9999" ]]; then
-	DEPEND+=" doc? ( >=dev-python/sphinx-1.1.3-r7 )"
-	DEPEND+=" >=sys-devel/flex-2.5.39-r1"
-	DEPEND+=" >=sys-devel/bison-2.4.3"
-	DEPEND+=" >=dev-python/docutils-0.12"
-fi
+DEPEND="${RDEPEND}"
 
 CONFIG_CHECK="~INOTIFY_USER"
 WARNING_INOTIFY_USER="CONFIG_INOTIFY_USER isn't set. Imfile module on this system will only support polling mode!"
@@ -107,35 +97,15 @@ pkg_setup() {
 }
 
 src_unpack() {
-	if [[ ${PV} == "9999" ]]; then
-		git-r3_fetch
-		git-r3_checkout
-	else
-		unpack ${P}.tar.gz
-	fi
+	unpack {{ artifacts['src'].final_name }} || die "Failed to unpack source tarball"
+	mv {{ github_user }}-{{ github_repo }}* "${S}" || die "Failed to rename unpacked source to '${S}'"
 
 	if use doc; then
-		if [[ ${PV} == "9999" ]]; then
-			local _EGIT_BRANCH=
-			if [[ -n "${EGIT_BRANCH}" ]]; then
-				# Cannot use rsyslog commits/branches for documentation repository
-				_EGIT_BRANCH=${EGIT_BRANCH}
-				unset EGIT_BRANCH
-			fi
-
-			git-r3_fetch "${DOC_REPO_URI}"
-			git-r3_checkout "${DOC_REPO_URI}" "${S}"/docs
-
-			if [[ -n "${_EGIT_BRANCH}" ]]; then
-				# Restore previous EGIT_BRANCH information
-				EGIT_BRANCH=${_EGIT_BRANCH}
-			fi
-		else
-			cd "${S}" || die "Cannot change dir into '${S}'"
-			mkdir docs || die "Failed to create docs directory"
-			cd docs || die "Failed to change dir into '${S}/docs'"
-			unpack ${PN}-doc-${PV}.tar.gz
-		fi
+		cd "${S}" || die "Cannot change dir into '${S}'"
+		mkdir docs || die "Failed to create docs directory"
+		cd docs || die "Failed to change dir into '${S}/docs'"
+		unpack {{ artifacts['doc'].final_name }} || die "Failed to unpack docs tarball"
+		mv {{ github_user }}-{{ doc_repo }}* ${PN}-doc-${PV} || die "Failed to move unpacked docs"
 	fi
 }
 
@@ -175,12 +145,14 @@ src_configure() {
 		$(use_enable test testbench)
 		$(use_enable test libfaketime)
 		$(use_enable test extended-tests)
-		# Input Plugins without depedencies
+		# Input Plugins without dependencies
+		--enable-imbatchreport
 		--enable-imdiag
 		--enable-imfile
+		--enable-improg
 		--enable-impstats
 		--enable-imptcp
-		# Message Modificiation Plugins without depedencies
+		# Message Modificiation Plugins without dependencies
 		--enable-mmanon
 		--enable-mmaudit
 		--enable-mmcount
@@ -189,6 +161,7 @@ src_configure() {
 		--enable-mmpstrucdata
 		--enable-mmrm1stspace
 		--enable-mmsequence
+		--enable-mmtaghostname
 		--enable-mmutf8fix
 		# Output Modification Plugins without dependencies
 		--enable-mail
@@ -198,10 +171,12 @@ src_configure() {
 		--enable-omuxsock
 		# Misc
 		--enable-fmhash
+		--enable-fmunflatten
 		$(use_enable xxhash fmhash-xxhash)
 		--enable-pmaixforwardedfrom
 		--enable-pmciscoios
 		--enable-pmcisconames
+		--enable-pmdb2diag
 		--enable-pmlastmsg
 		$(use_enable normalize pmnormalize)
 		--enable-pmnull
@@ -212,6 +187,7 @@ src_configure() {
 		$(use_enable mongodb ommongodb)
 		$(use_enable mysql)
 		$(use_enable postgres pgsql)
+		$(use_enable redis imhiredis)
 		$(use_enable redis omhiredis)
 		# Debug
 		$(use_enable debug)
@@ -222,6 +198,8 @@ src_configure() {
 		$(use_enable curl fmhttp)
 		$(use_enable elasticsearch)
 		$(use_enable gcrypt libgcrypt)
+		$(use_enable imhttp)
+		$(use_enable impcap)
 		$(use_enable jemalloc)
 		$(use_enable kafka imkafka)
 		$(use_enable kafka omkafka)
@@ -304,6 +282,8 @@ src_install() {
 	newconfd "${FILESDIR}/${PN}.confd-r1" ${PN}
 	newinitd "${FILESDIR}/${PN}.initd-r1" ${PN}
 
+	use systemd && systemd_newunit "${FILESDIR}/${PN}.service" ${PN}.service
+
 	keepdir /var/empty/dev
 	keepdir /var/spool/${PN}
 	keepdir /etc/ssl/${PN}
@@ -319,16 +299,16 @@ src_install() {
 	newins "${FILESDIR}/${PN}-r1.logrotate" ${PN}
 
 	if use mysql; then
-		insinto /usr/share/doc/${PF}/scripts/mysql
+		insinto /usr/share/${PN}/scripts/mysql
 		doins plugins/ommysql/createDB.sql
 	fi
 
 	if use postgres; then
-		insinto /usr/share/doc/${PF}/scripts/pgsql
+		insinto /usr/share/${PN}/scripts/pgsql
 		doins plugins/ompgsql/createDB.sql
 	fi
 
-	prune_libtool_files --modules
+	find "${ED}" -name '*.la' -delete || die
 }
 
 pkg_postinst() {
@@ -368,10 +348,14 @@ pkg_postinst() {
 }
 
 pkg_config() {
-	if ! use ssl ; then
+	if ! use ssl; then
 		einfo "There is nothing to configure for rsyslog unless you"
 		einfo "used USE=ssl to build it."
 		return 0
+	fi
+
+	if ! hash certtool &>/dev/null; then
+		die "certtool not found! Is net-libs/gnutls[tools] is installed?"
 	fi
 
 	# Make sure the certificates directory exists
@@ -385,7 +369,7 @@ pkg_config() {
 	if [[ ! -f "${CERTDIR}/${PN}_ca.cert.pem" ]]; then
 		einfo "No CA key and certificate found in ${CERTDIR}, creating them for you..."
 		certtool --generate-privkey \
-			--outfile "${CERTDIR}/${PN}_ca.privkey.pem" &>/dev/null
+			--outfile "${CERTDIR}/${PN}_ca.privkey.pem" || die
 		chmod 400 "${CERTDIR}/${PN}_ca.privkey.pem"
 
 		cat > "${T}/${PF}.$$" <<- _EOF
@@ -398,7 +382,7 @@ pkg_config() {
 		certtool --generate-self-signed \
 			--load-privkey "${CERTDIR}/${PN}_ca.privkey.pem" \
 			--outfile "${CERTDIR}/${PN}_ca.cert.pem" \
-			--template "${T}/${PF}.$$" &>/dev/null
+			--template "${T}/${PF}.$$" || die
 		chmod 400 "${CERTDIR}/${PN}_ca.privkey.pem"
 
 		# Create the server certificate
@@ -408,7 +392,7 @@ pkg_config() {
 
 		einfo "Creating private key and certificate for server ${CN}..."
 		certtool --generate-privkey \
-			--outfile "${CERTDIR}/${PN}_${CN}.key.pem" &>/dev/null
+			--outfile "${CERTDIR}/${PN}_${CN}.key.pem" || die
 		chmod 400 "${CERTDIR}/${PN}_${CN}.key.pem"
 
 		cat > "${T}/${PF}.$$" <<- _EOF
@@ -437,7 +421,7 @@ pkg_config() {
 
 	einfo "Creating private key and certificate for client ${CN}..."
 	certtool --generate-privkey \
-		--outfile "${CERTDIR}/${PN}_${CN}.key.pem" &>/dev/null
+		--outfile "${CERTDIR}/${PN}_${CN}.key.pem" || die
 	chmod 400 "${CERTDIR}/${PN}_${CN}.key.pem"
 
 	cat > "${T}/${PF}.$$" <<- _EOF
@@ -452,7 +436,7 @@ pkg_config() {
 		--load-privkey "${CERTDIR}/${PN}_${CN}.key.pem" \
 		--load-ca-certificate "${CERTDIR}/${PN}_ca.cert.pem" \
 		--load-ca-privkey "${CERTDIR}/${PN}_ca.privkey.pem" \
-		--template "${T}/${PF}.$$" &>/dev/null
+		--template "${T}/${PF}.$$" || die
 	chmod 400 "${CERTDIR}/${PN}_${CN}.cert.pem"
 
 	rm -f "${T}/${PF}.$$"
